/*
A game generates dungeon layout depending on number of simultaneous players (Max. 8).
The dungeon has linear layout, generated by attaching rooms to end of the each other.
The generation algorithm takes care that each kind of room occurs at least once.
The Types of Rooms are as follows
CORRIDOR, CROSSROADS, SHRINE, TREASURE, ARENA, BOSS
NOTE : ALL FLOATS ARE ROUNDED DOWN
Rules for Generating Dungeon
1. The length of the dungeon is 4 times the number of players. However, minimum length is 14
2. The dungeon must start with a SHRINE
3. The dungeon must end with a BOSS room followed by TREASURE room.
4. A dungeon also has multiple ARENA rooms, the number of which is half the number of players, rounded to nearest lower integer, However minimum 1 arena must be present.
5. ARENA rooms are equally distributed along the length of the remaining unfilled dungeon after starting SHRINE and ending BOSS and TREASURE has been filled out.
6. A SHRINE is always placed before ARENA rooms
7. Every ARENA is always followed by TREASURE room
8. A CROSSROADS is always occurring before every SHRINE except the starting one.
9. Remaining empty rooms can be filled out with CORRIDOR type rooms.
e.g.
Input :
4
Output :
SHRINE
CORRIDOR
CORRIDOR
CROSSROADS
SHRINE
ARENA
TREASURE
CORRIDOR
CROSSROADS
SHRINE
ARENA
TREASURE
CORRIDOR
CORRIDOR
BOSS
TREASURE
*/

function generateDungeon(players) {
    let length = Math.max(4 * players, 14);
    let layout = new Array(length).fill('CORRIDOR');

    layout[0] = 'SHRINE';
    layout[length - 2] = 'BOSS';
    layout[length - 1] = 'TREASURE';

    let arenaCount = Math.max(Math.floor(players / 2), 1);
    let availableSlots = length - 3; // after first SHRINE and before last BOSS+TREASURE
    let positions = [];

    for (let i = 1; i <= arenaCount; i++) {
        let pos = Math.floor(i * (availableSlots / (arenaCount + 1)));
        positions.push(pos);
    }

    for (let pos of positions) {
        layout[pos - 2] = 'CROSSROADS';
        layout[pos - 1] = 'SHRINE';
        layout[pos] = 'ARENA';
        layout[pos + 1] = 'TREASURE';
    }

    return layout;
}


const input2 = 4;
const dungeonLayout = generateDungeon(input2);
console.log(dungeonLayout.join('\n'));
